name: Bash CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

env:
  TERM: xterm

jobs:
  steps:
    name: Bash Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run ShellCheck on jade-diy
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC1091

      - name: Run shfmt on jade-diy scripts
        uses: luizm/action-sh-checker@master
        env:
          SHFMT_OPTS: -i 2 -sr
        with:
          sh_checker_shellcheck_disable: true

      - name: Install dependency python3-virtualenv
        run: sudo apt update && sudo apt install -y python3-virtualenv

      - name: Run flash_your_device
        run: timeout 200 /bin/bash -x ./flash_your_device

      - name: Run flash_the_ttgo_tdisplay
        run: timeout 200 /bin/bash -x ./device_specific/flash_the_ttgo_tdisplay

      - name: Run flash_the_m5stack_m5stickc_plus
        run: timeout 200 /bin/bash -x ./device_specific/flash_the_m5stack_m5stickc_plus

      - name: Run flash_the_m5stack_core_basic
        run: timeout 200 /bin/bash -x ./device_specific/flash_the_m5stack_core_basic

      - name: Run flash_the_m5stack_fire
        run: timeout 200 /bin/bash -x ./device_specific/flash_the_m5stack_fire
