name: Bash CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  shellcheck:
    name: Validation with ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck on jade-diy
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC1091
  shfmt-checker:
    name: Validation with shfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run shfmt on jade-diy scripts
        uses: luizm/action-sh-checker@master
        env:
          SHFMT_OPTS: -i 2 -sr
        with:
          sh_checker_shellcheck_disable: true
