name: Validation CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

env:
  TERM: xterm

jobs:
  bash-lint:
    name: Validate with ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck on jade-diy
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC1091

  bash-format:
    name: Validate with shfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run shfmt on jade-diy scripts
        uses: luizm/action-sh-checker@master
        env:
          SHFMT_OPTS: -i 2 -sr
        with:
          sh_checker_shellcheck_disable: true

  markdown-links:
    name: Validation with markdown-link-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run markdown-link-check on Documentation
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'

  run-scripts:
    name: Execute the scripts
    runs-on: ubuntu-latest
    needs: [bash-lint, bash-format]
    steps:
      - uses: actions/checkout@v4
      - name: Install runtime dependency python3-virtualenv
        run: sudo apt update && sudo apt install -y python3-virtualenv
      - name: Run flash_the_ttgo_tdisplay
        run: timeout 300 /bin/bash -x ./device_specific/flash_the_ttgo_tdisplay
      - name: Run flash_the_m5stack_m5stickc_plus
        run: timeout 20 /bin/bash -x ./device_specific/flash_the_m5stack_m5stickc_plus
      - name: Run flash_the_m5stack_core_basic
        run: timeout 20 /bin/bash -x ./device_specific/flash_the_m5stack_core_basic
      - name: Run flash_the_m5stack_fire
        run: timeout 20 /bin/bash -x ./device_specific/flash_the_m5stack_fire
      - name: Run flash_your_device
        run: timeout 60 /bin/bash -x ./flash_your_device
